export let CONST = {
    score: 0,
    highscore: 0,
    gridRows: 8,
    gridColumns: 8,
    tileWidth: 64,
    tileHeight: 72,
    candyTypes: [
        'cookie1',
        'cookie2',
        'croissant',
        'cupcake',
        // 'donut',
        // 'eclair',
        // 'macaroon',
        // 'pie',
        // 'poptart1',
        // 'poptart2',
        // 'starcookie1',
        // 'starcookie2',
    ],
}
